// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gc/proto/formula.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 数据类型
type Type int32

const (
	Type_FLOAT    Type = 0
	Type_STRING   Type = 1
	Type_BOOLEAN  Type = 2
	Type_DATETIME Type = 3
)

var Type_name = map[int32]string{
	0: "FLOAT",
	1: "STRING",
	2: "BOOLEAN",
	3: "DATETIME",
}

var Type_value = map[string]int32{
	"FLOAT":    0,
	"STRING":   1,
	"BOOLEAN":  2,
	"DATETIME": 3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{0}
}

type Operator int32

const (
	// 算数运算
	Operator_ADD      Operator = 0
	Operator_SUBTRACT Operator = 1
	Operator_MULTIPLY Operator = 2
	Operator_DIVIDE   Operator = 3
	Operator_MOD      Operator = 4
	Operator_POW      Operator = 5
	Operator_EXP      Operator = 6
	Operator_SQRT     Operator = 7
	Operator_LN       Operator = 8
	Operator_LOG2     Operator = 9
	Operator_LOG10    Operator = 10
	Operator_ABS      Operator = 11
	Operator_CEIL     Operator = 12
	Operator_TRUNC    Operator = 13
	Operator_FLOOR    Operator = 14
	// 关系运算
	Operator_EQ     Operator = 15
	Operator_NE     Operator = 16
	Operator_LT     Operator = 17
	Operator_LTE    Operator = 18
	Operator_GT     Operator = 19
	Operator_GTE    Operator = 20
	Operator_EXISTS Operator = 21
	// 逻辑运算
	Operator_AND Operator = 22
	Operator_OR  Operator = 23
	Operator_NOT Operator = 24
	// 选择
	Operator_COND Operator = 25
	// 字符串
	Operator_REGEX   Operator = 26
	Operator_CONCATE Operator = 27
	Operator_SUM     Operator = 28
	Operator_AVG     Operator = 29
	Operator_MAX     Operator = 30
	Operator_MIN     Operator = 31
	Operator_COUNT   Operator = 32
	// 日期解析
	Operator_YEAR  Operator = 33
	Operator_MONTH Operator = 34
	Operator_DAY   Operator = 35
	//内容拼接
	Operator_STRING_AGG Operator = 36
)

var Operator_name = map[int32]string{
	0:  "ADD",
	1:  "SUBTRACT",
	2:  "MULTIPLY",
	3:  "DIVIDE",
	4:  "MOD",
	5:  "POW",
	6:  "EXP",
	7:  "SQRT",
	8:  "LN",
	9:  "LOG2",
	10: "LOG10",
	11: "ABS",
	12: "CEIL",
	13: "TRUNC",
	14: "FLOOR",
	15: "EQ",
	16: "NE",
	17: "LT",
	18: "LTE",
	19: "GT",
	20: "GTE",
	21: "EXISTS",
	22: "AND",
	23: "OR",
	24: "NOT",
	25: "COND",
	26: "REGEX",
	27: "CONCATE",
	28: "SUM",
	29: "AVG",
	30: "MAX",
	31: "MIN",
	32: "COUNT",
	33: "YEAR",
	34: "MONTH",
	35: "DAY",
	36: "STRING_AGG",
}

var Operator_value = map[string]int32{
	"ADD":        0,
	"SUBTRACT":   1,
	"MULTIPLY":   2,
	"DIVIDE":     3,
	"MOD":        4,
	"POW":        5,
	"EXP":        6,
	"SQRT":       7,
	"LN":         8,
	"LOG2":       9,
	"LOG10":      10,
	"ABS":        11,
	"CEIL":       12,
	"TRUNC":      13,
	"FLOOR":      14,
	"EQ":         15,
	"NE":         16,
	"LT":         17,
	"LTE":        18,
	"GT":         19,
	"GTE":        20,
	"EXISTS":     21,
	"AND":        22,
	"OR":         23,
	"NOT":        24,
	"COND":       25,
	"REGEX":      26,
	"CONCATE":    27,
	"SUM":        28,
	"AVG":        29,
	"MAX":        30,
	"MIN":        31,
	"COUNT":      32,
	"YEAR":       33,
	"MONTH":      34,
	"DAY":        35,
	"STRING_AGG": 36,
}

func (x Operator) String() string {
	return proto.EnumName(Operator_name, int32(x))
}

func (Operator) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{1}
}

type Join_Method int32

const (
	Join_INNER Join_Method = 0
	Join_LEFT  Join_Method = 1
	Join_RIGHT Join_Method = 2
	Join_FULL  Join_Method = 3
)

var Join_Method_name = map[int32]string{
	0: "INNER",
	1: "LEFT",
	2: "RIGHT",
	3: "FULL",
}

var Join_Method_value = map[string]int32{
	"INNER": 0,
	"LEFT":  1,
	"RIGHT": 2,
	"FULL":  3,
}

func (x Join_Method) String() string {
	return proto.EnumName(Join_Method_name, int32(x))
}

func (Join_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{6, 0}
}

// 一套流水线，输入多张表，中间产生多张表，输出多张表
type Pipeline struct {
	Collections          []*Collection     `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	Path                 string            `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name                 string            `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ResultMetaName       string            `protobuf:"bytes,4,opt,name=result_meta_name,json=resultMetaName,proto3" json:"result_meta_name,omitempty"`
	TaxType              string            `protobuf:"bytes,5,opt,name=tax_type,json=taxType,proto3" json:"tax_type,omitempty"`
	IndustryCode         string            `protobuf:"bytes,6,opt,name=industry_code,json=industryCode,proto3" json:"industry_code,omitempty"`
	IndustryName         string            `protobuf:"bytes,7,opt,name=industry_name,json=industryName,proto3" json:"industry_name,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Pipeline) Reset()         { *m = Pipeline{} }
func (m *Pipeline) String() string { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()    {}
func (*Pipeline) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{0}
}

func (m *Pipeline) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pipeline.Unmarshal(m, b)
}
func (m *Pipeline) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pipeline.Marshal(b, m, deterministic)
}
func (m *Pipeline) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pipeline.Merge(m, src)
}
func (m *Pipeline) XXX_Size() int {
	return xxx_messageInfo_Pipeline.Size(m)
}
func (m *Pipeline) XXX_DiscardUnknown() {
	xxx_messageInfo_Pipeline.DiscardUnknown(m)
}

var xxx_messageInfo_Pipeline proto.InternalMessageInfo

func (m *Pipeline) GetCollections() []*Collection {
	if m != nil {
		return m.Collections
	}
	return nil
}

func (m *Pipeline) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetResultMetaName() string {
	if m != nil {
		return m.ResultMetaName
	}
	return ""
}

func (m *Pipeline) GetTaxType() string {
	if m != nil {
		return m.TaxType
	}
	return ""
}

func (m *Pipeline) GetIndustryCode() string {
	if m != nil {
		return m.IndustryCode
	}
	return ""
}

func (m *Pipeline) GetIndustryName() string {
	if m != nil {
		return m.IndustryName
	}
	return ""
}

func (m *Pipeline) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

// 一个表
type Collection struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*Collection_Input
	//	*Collection_Sample
	//	*Collection_Projection
	//	*Collection_Filter
	//	*Collection_Join
	//	*Collection_Group
	Body                 isCollection_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{1}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isCollection_Body interface {
	isCollection_Body()
}

type Collection_Input struct {
	Input *Input `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type Collection_Sample struct {
	Sample *Sample `protobuf:"bytes,3,opt,name=sample,proto3,oneof"`
}

type Collection_Projection struct {
	Projection *Projection `protobuf:"bytes,4,opt,name=projection,proto3,oneof"`
}

type Collection_Filter struct {
	Filter *Filter `protobuf:"bytes,5,opt,name=filter,proto3,oneof"`
}

type Collection_Join struct {
	Join *Join `protobuf:"bytes,6,opt,name=join,proto3,oneof"`
}

type Collection_Group struct {
	Group *Group `protobuf:"bytes,7,opt,name=group,proto3,oneof"`
}

func (*Collection_Input) isCollection_Body() {}

func (*Collection_Sample) isCollection_Body() {}

func (*Collection_Projection) isCollection_Body() {}

func (*Collection_Filter) isCollection_Body() {}

func (*Collection_Join) isCollection_Body() {}

func (*Collection_Group) isCollection_Body() {}

func (m *Collection) GetBody() isCollection_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Collection) GetInput() *Input {
	if x, ok := m.GetBody().(*Collection_Input); ok {
		return x.Input
	}
	return nil
}

func (m *Collection) GetSample() *Sample {
	if x, ok := m.GetBody().(*Collection_Sample); ok {
		return x.Sample
	}
	return nil
}

func (m *Collection) GetProjection() *Projection {
	if x, ok := m.GetBody().(*Collection_Projection); ok {
		return x.Projection
	}
	return nil
}

func (m *Collection) GetFilter() *Filter {
	if x, ok := m.GetBody().(*Collection_Filter); ok {
		return x.Filter
	}
	return nil
}

func (m *Collection) GetJoin() *Join {
	if x, ok := m.GetBody().(*Collection_Join); ok {
		return x.Join
	}
	return nil
}

func (m *Collection) GetGroup() *Group {
	if x, ok := m.GetBody().(*Collection_Group); ok {
		return x.Group
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Collection) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Collection_Input)(nil),
		(*Collection_Sample)(nil),
		(*Collection_Projection)(nil),
		(*Collection_Filter)(nil),
		(*Collection_Join)(nil),
		(*Collection_Group)(nil),
	}
}

// 输入表
type Input struct {
	MetaName             string   `protobuf:"bytes,1,opt,name=meta_name,json=metaName,proto3" json:"meta_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{2}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetMetaName() string {
	if m != nil {
		return m.MetaName
	}
	return ""
}

// 随机取样，对一个表的行以一定概率随机取样，维持列名不变
type Sample struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Rate                 float64  `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{3}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Sample) GetRate() float64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

// 投影操作
type Projection struct {
	Input                string              `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Fields               []*Projection_Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Projection) Reset()         { *m = Projection{} }
func (m *Projection) String() string { return proto.CompactTextString(m) }
func (*Projection) ProtoMessage()    {}
func (*Projection) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{4}
}

func (m *Projection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projection.Unmarshal(m, b)
}
func (m *Projection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projection.Marshal(b, m, deterministic)
}
func (m *Projection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projection.Merge(m, src)
}
func (m *Projection) XXX_Size() int {
	return xxx_messageInfo_Projection.Size(m)
}
func (m *Projection) XXX_DiscardUnknown() {
	xxx_messageInfo_Projection.DiscardUnknown(m)
}

var xxx_messageInfo_Projection proto.InternalMessageInfo

func (m *Projection) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Projection) GetFields() []*Projection_Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Projection_Field struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expression           *Expression `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Projection_Field) Reset()         { *m = Projection_Field{} }
func (m *Projection_Field) String() string { return proto.CompactTextString(m) }
func (*Projection_Field) ProtoMessage()    {}
func (*Projection_Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{4, 0}
}

func (m *Projection_Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Projection_Field.Unmarshal(m, b)
}
func (m *Projection_Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Projection_Field.Marshal(b, m, deterministic)
}
func (m *Projection_Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Projection_Field.Merge(m, src)
}
func (m *Projection_Field) XXX_Size() int {
	return xxx_messageInfo_Projection_Field.Size(m)
}
func (m *Projection_Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Projection_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Projection_Field proto.InternalMessageInfo

func (m *Projection_Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Projection_Field) GetExpression() *Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

// 过滤操作
type Filter struct {
	Input                string      `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Expression           *Expression `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{5}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Filter) GetExpression() *Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

// 连接操作
type Join struct {
	LeftInput            string            `protobuf:"bytes,1,opt,name=left_input,json=leftInput,proto3" json:"left_input,omitempty"`
	RightInput           string            `protobuf:"bytes,2,opt,name=right_input,json=rightInput,proto3" json:"right_input,omitempty"`
	Conditions           []*Join_Condition `protobuf:"bytes,3,rep,name=conditions,proto3" json:"conditions,omitempty"`
	LeftFields           []*Join_Field     `protobuf:"bytes,4,rep,name=left_fields,json=leftFields,proto3" json:"left_fields,omitempty"`
	RightFields          []*Join_Field     `protobuf:"bytes,5,rep,name=right_fields,json=rightFields,proto3" json:"right_fields,omitempty"`
	Method               Join_Method       `protobuf:"varint,6,opt,name=method,proto3,enum=proto.Join_Method" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{6}
}

func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (m *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(m, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetLeftInput() string {
	if m != nil {
		return m.LeftInput
	}
	return ""
}

func (m *Join) GetRightInput() string {
	if m != nil {
		return m.RightInput
	}
	return ""
}

func (m *Join) GetConditions() []*Join_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *Join) GetLeftFields() []*Join_Field {
	if m != nil {
		return m.LeftFields
	}
	return nil
}

func (m *Join) GetRightFields() []*Join_Field {
	if m != nil {
		return m.RightFields
	}
	return nil
}

func (m *Join) GetMethod() Join_Method {
	if m != nil {
		return m.Method
	}
	return Join_INNER
}

// 左边表的一列等于右边表的一列
type Join_Condition struct {
	Left                 string   `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                string   `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Join_Condition) Reset()         { *m = Join_Condition{} }
func (m *Join_Condition) String() string { return proto.CompactTextString(m) }
func (*Join_Condition) ProtoMessage()    {}
func (*Join_Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{6, 0}
}

func (m *Join_Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join_Condition.Unmarshal(m, b)
}
func (m *Join_Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join_Condition.Marshal(b, m, deterministic)
}
func (m *Join_Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join_Condition.Merge(m, src)
}
func (m *Join_Condition) XXX_Size() int {
	return xxx_messageInfo_Join_Condition.Size(m)
}
func (m *Join_Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Join_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Join_Condition proto.InternalMessageInfo

func (m *Join_Condition) GetLeft() string {
	if m != nil {
		return m.Left
	}
	return ""
}

func (m *Join_Condition) GetRight() string {
	if m != nil {
		return m.Right
	}
	return ""
}

// 输出的一列
type Join_Field struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Field                string   `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Join_Field) Reset()         { *m = Join_Field{} }
func (m *Join_Field) String() string { return proto.CompactTextString(m) }
func (*Join_Field) ProtoMessage()    {}
func (*Join_Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{6, 1}
}

func (m *Join_Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join_Field.Unmarshal(m, b)
}
func (m *Join_Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join_Field.Marshal(b, m, deterministic)
}
func (m *Join_Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join_Field.Merge(m, src)
}
func (m *Join_Field) XXX_Size() int {
	return xxx_messageInfo_Join_Field.Size(m)
}
func (m *Join_Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Join_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Join_Field proto.InternalMessageInfo

func (m *Join_Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Join_Field) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

// 分组运算操作
type Group struct {
	Input                string         `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Keys                 []string       `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	Fields               []*Group_Field `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{7}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *Group) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *Group) GetFields() []*Group_Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type Group_Field struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expression           *Expression `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Group_Field) Reset()         { *m = Group_Field{} }
func (m *Group_Field) String() string { return proto.CompactTextString(m) }
func (*Group_Field) ProtoMessage()    {}
func (*Group_Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{7, 0}
}

func (m *Group_Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group_Field.Unmarshal(m, b)
}
func (m *Group_Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group_Field.Marshal(b, m, deterministic)
}
func (m *Group_Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group_Field.Merge(m, src)
}
func (m *Group_Field) XXX_Size() int {
	return xxx_messageInfo_Group_Field.Size(m)
}
func (m *Group_Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Group_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Group_Field proto.InternalMessageInfo

func (m *Group_Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group_Field) GetExpression() *Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

// 单表内的运算
type Expression struct {
	// Types that are valid to be assigned to Body:
	//	*Expression_Literal
	//	*Expression_Field
	//	*Expression_Operation
	Body                 isExpression_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{8}
}

func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

type isExpression_Body interface {
	isExpression_Body()
}

type Expression_Literal struct {
	Literal *Literal `protobuf:"bytes,1,opt,name=literal,proto3,oneof"`
}

type Expression_Field struct {
	Field string `protobuf:"bytes,2,opt,name=field,proto3,oneof"`
}

type Expression_Operation struct {
	Operation *Operation `protobuf:"bytes,3,opt,name=operation,proto3,oneof"`
}

func (*Expression_Literal) isExpression_Body() {}

func (*Expression_Field) isExpression_Body() {}

func (*Expression_Operation) isExpression_Body() {}

func (m *Expression) GetBody() isExpression_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Expression) GetLiteral() *Literal {
	if x, ok := m.GetBody().(*Expression_Literal); ok {
		return x.Literal
	}
	return nil
}

func (m *Expression) GetField() string {
	if x, ok := m.GetBody().(*Expression_Field); ok {
		return x.Field
	}
	return ""
}

func (m *Expression) GetOperation() *Operation {
	if x, ok := m.GetBody().(*Expression_Operation); ok {
		return x.Operation
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Expression) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Expression_Literal)(nil),
		(*Expression_Field)(nil),
		(*Expression_Operation)(nil),
	}
}

// 字面常量
type Literal struct {
	// Types that are valid to be assigned to Body:
	//	*Literal_FloatValue
	//	*Literal_StringValue
	//	*Literal_BooleanValue
	Body                 isLiteral_Body `protobuf_oneof:"body"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Literal) Reset()         { *m = Literal{} }
func (m *Literal) String() string { return proto.CompactTextString(m) }
func (*Literal) ProtoMessage()    {}
func (*Literal) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{9}
}

func (m *Literal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Literal.Unmarshal(m, b)
}
func (m *Literal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Literal.Marshal(b, m, deterministic)
}
func (m *Literal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Literal.Merge(m, src)
}
func (m *Literal) XXX_Size() int {
	return xxx_messageInfo_Literal.Size(m)
}
func (m *Literal) XXX_DiscardUnknown() {
	xxx_messageInfo_Literal.DiscardUnknown(m)
}

var xxx_messageInfo_Literal proto.InternalMessageInfo

type isLiteral_Body interface {
	isLiteral_Body()
}

type Literal_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,1,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Literal_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Literal_BooleanValue struct {
	BooleanValue bool `protobuf:"varint,3,opt,name=boolean_value,json=booleanValue,proto3,oneof"`
}

func (*Literal_FloatValue) isLiteral_Body() {}

func (*Literal_StringValue) isLiteral_Body() {}

func (*Literal_BooleanValue) isLiteral_Body() {}

func (m *Literal) GetBody() isLiteral_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Literal) GetFloatValue() float64 {
	if x, ok := m.GetBody().(*Literal_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *Literal) GetStringValue() string {
	if x, ok := m.GetBody().(*Literal_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *Literal) GetBooleanValue() bool {
	if x, ok := m.GetBody().(*Literal_BooleanValue); ok {
		return x.BooleanValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Literal) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Literal_FloatValue)(nil),
		(*Literal_StringValue)(nil),
		(*Literal_BooleanValue)(nil),
	}
}

// 计算
type Operation struct {
	Operator             Operator      `protobuf:"varint,1,opt,name=operator,proto3,enum=proto.Operator" json:"operator,omitempty"`
	Operands             []*Expression `protobuf:"bytes,2,rep,name=operands,proto3" json:"operands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d99441d876fb8ba2, []int{10}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetOperator() Operator {
	if m != nil {
		return m.Operator
	}
	return Operator_ADD
}

func (m *Operation) GetOperands() []*Expression {
	if m != nil {
		return m.Operands
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.Type", Type_name, Type_value)
	proto.RegisterEnum("proto.Operator", Operator_name, Operator_value)
	proto.RegisterEnum("proto.Join_Method", Join_Method_name, Join_Method_value)
	proto.RegisterType((*Pipeline)(nil), "proto.Pipeline")
	proto.RegisterMapType((map[string]string)(nil), "proto.Pipeline.TagsEntry")
	proto.RegisterType((*Collection)(nil), "proto.Collection")
	proto.RegisterType((*Input)(nil), "proto.Input")
	proto.RegisterType((*Sample)(nil), "proto.Sample")
	proto.RegisterType((*Projection)(nil), "proto.Projection")
	proto.RegisterType((*Projection_Field)(nil), "proto.Projection.Field")
	proto.RegisterType((*Filter)(nil), "proto.Filter")
	proto.RegisterType((*Join)(nil), "proto.Join")
	proto.RegisterType((*Join_Condition)(nil), "proto.Join.Condition")
	proto.RegisterType((*Join_Field)(nil), "proto.Join.Field")
	proto.RegisterType((*Group)(nil), "proto.Group")
	proto.RegisterType((*Group_Field)(nil), "proto.Group.Field")
	proto.RegisterType((*Expression)(nil), "proto.Expression")
	proto.RegisterType((*Literal)(nil), "proto.Literal")
	proto.RegisterType((*Operation)(nil), "proto.Operation")
}

func init() { proto.RegisterFile("gc/proto/formula.proto", fileDescriptor_d99441d876fb8ba2) }

var fileDescriptor_d99441d876fb8ba2 = []byte{
	// 1169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x73, 0xda, 0x56,
	0x17, 0x46, 0x80, 0xf8, 0x38, 0xc2, 0xce, 0xc9, 0x7d, 0xf3, 0x41, 0x9c, 0x37, 0x4d, 0x42, 0xd2,
	0x69, 0xc6, 0x9d, 0x38, 0x09, 0x69, 0xa6, 0x99, 0xee, 0x30, 0xc8, 0x40, 0x47, 0x48, 0xce, 0x45,
	0x4e, 0x9d, 0x15, 0xa3, 0x18, 0x99, 0x28, 0x91, 0x11, 0x23, 0x44, 0xc7, 0xec, 0xba, 0xee, 0x8f,
	0xe8, 0xa6, 0xeb, 0x2e, 0xfa, 0x87, 0xfa, 0x4f, 0x3a, 0xd3, 0x39, 0xe7, 0x0a, 0x01, 0xd3, 0xb8,
	0x8b, 0xce, 0x74, 0xc5, 0xbd, 0xcf, 0x79, 0xce, 0xd7, 0x73, 0x8f, 0x0e, 0x70, 0x6b, 0x72, 0xf6,
	0x6c, 0x16, 0x47, 0x49, 0xf4, 0xec, 0x3c, 0x8a, 0x2f, 0x16, 0xa1, 0x77, 0xc0, 0x37, 0xa1, 0xf3,
	0x4f, 0xe3, 0x8f, 0x3c, 0x54, 0x8e, 0x83, 0x99, 0x1f, 0x06, 0x53, 0x5f, 0xbc, 0x04, 0xe3, 0x2c,
	0x0a, 0x43, 0xff, 0x2c, 0x09, 0xa2, 0xe9, 0xbc, 0xae, 0x3d, 0x28, 0x3c, 0x31, 0x9a, 0xd7, 0x95,
	0xc3, 0x41, 0x3b, 0xb3, 0xc8, 0x4d, 0x96, 0x10, 0x50, 0x9c, 0x79, 0xc9, 0x87, 0x7a, 0xfe, 0x81,
	0xf6, 0xa4, 0x2a, 0xf9, 0x4c, 0xd8, 0xd4, 0xbb, 0xf0, 0xeb, 0x05, 0x85, 0xd1, 0x59, 0x3c, 0x01,
	0x8c, 0xfd, 0xf9, 0x22, 0x4c, 0x46, 0x17, 0x7e, 0xe2, 0x8d, 0xd8, 0x5e, 0x64, 0xfb, 0xae, 0xc2,
	0x07, 0x7e, 0xe2, 0xd9, 0xc4, 0xbc, 0x03, 0x95, 0xc4, 0xbb, 0x1c, 0x25, 0xcb, 0x99, 0x5f, 0xd7,
	0x99, 0x51, 0x4e, 0xbc, 0x4b, 0x77, 0x39, 0xf3, 0xc5, 0x23, 0xd8, 0x09, 0xa6, 0xe3, 0xc5, 0x3c,
	0x89, 0x97, 0xa3, 0xb3, 0x68, 0xec, 0xd7, 0x4b, 0x6c, 0xaf, 0xad, 0xc0, 0x76, 0x34, 0xde, 0x26,
	0x71, 0x9a, 0xf2, 0x36, 0x89, 0x93, 0x3c, 0x85, 0x62, 0xe2, 0x4d, 0xe6, 0xf5, 0x0a, 0x37, 0x79,
	0x27, 0x6d, 0x72, 0x25, 0xc5, 0x81, 0xeb, 0x4d, 0xe6, 0xe6, 0x34, 0x89, 0x97, 0x92, 0x69, 0x7b,
	0xdf, 0x42, 0x35, 0x83, 0x04, 0x42, 0xe1, 0x93, 0xbf, 0xac, 0x6b, 0x1c, 0x96, 0x8e, 0xe2, 0x06,
	0xe8, 0x3f, 0x7a, 0xe1, 0xc2, 0x4f, 0x55, 0x50, 0x97, 0xef, 0xf2, 0xaf, 0xb5, 0xc6, 0x2f, 0x79,
	0x80, 0xb5, 0x74, 0x99, 0x32, 0xda, 0x86, 0x32, 0x8f, 0x41, 0x0f, 0xa6, 0xb3, 0x45, 0xc2, 0xce,
	0x46, 0xb3, 0x96, 0xd6, 0xd2, 0x27, 0xac, 0x97, 0x93, 0xca, 0x28, 0xbe, 0x82, 0xd2, 0xdc, 0xbb,
	0x98, 0x85, 0x4a, 0x55, 0xa3, 0xb9, 0x93, 0xd2, 0x86, 0x0c, 0xf6, 0x72, 0x32, 0x35, 0x8b, 0x97,
	0x00, 0xb3, 0x38, 0xfa, 0xa8, 0x12, 0xb2, 0xc4, 0xeb, 0x47, 0x3c, 0xce, 0x0c, 0xbd, 0x9c, 0xdc,
	0xa0, 0x51, 0xf4, 0xf3, 0x20, 0x4c, 0xfc, 0x98, 0x15, 0x5f, 0x47, 0x3f, 0x62, 0x90, 0xa2, 0x2b,
	0xb3, 0x78, 0x08, 0xc5, 0x8f, 0x51, 0x30, 0x65, 0xe1, 0x8d, 0xa6, 0x91, 0xd2, 0xbe, 0x8f, 0x02,
	0x8a, 0xc8, 0x26, 0xea, 0x67, 0x12, 0x47, 0x8b, 0x19, 0xeb, 0xbe, 0xee, 0xa7, 0x4b, 0x18, 0xf5,
	0xc3, 0xc6, 0xc3, 0x12, 0x14, 0xdf, 0x47, 0xe3, 0x65, 0xe3, 0x31, 0xe8, 0xdc, 0xa9, 0xb8, 0x0b,
	0xd5, 0xf5, 0x64, 0x28, 0x7d, 0x2a, 0x17, 0xe9, 0x4c, 0x34, 0x9a, 0x50, 0x52, 0x8d, 0x92, 0xd4,
	0x4a, 0x2d, 0x45, 0x49, 0xd5, 0x11, 0x50, 0x8c, 0xbd, 0x44, 0xe9, 0xaf, 0x49, 0x3e, 0x37, 0x7e,
	0xd5, 0x00, 0xd6, 0x0d, 0x5f, 0xe1, 0xf8, 0x8c, 0x1a, 0xf7, 0xc3, 0xf1, 0xbc, 0x9e, 0xe7, 0x49,
	0xb8, 0xfd, 0x37, 0xa5, 0x0e, 0x8e, 0xc8, 0x2e, 0x53, 0xda, 0x9e, 0x0d, 0x3a, 0x03, 0x9f, 0x7d,
	0xca, 0x17, 0x00, 0xfe, 0xe5, 0x2c, 0xf6, 0xe7, 0x73, 0xd2, 0x3e, 0xbf, 0xa5, 0xbd, 0x99, 0x19,
	0xe4, 0x06, 0xa9, 0xf1, 0x06, 0x4a, 0x4a, 0xe4, 0x2b, 0x0a, 0xfc, 0x17, 0x21, 0x7f, 0x2f, 0x40,
	0x91, 0x5e, 0x44, 0xdc, 0x03, 0x08, 0xfd, 0xf3, 0x64, 0xb4, 0x19, 0xb6, 0x4a, 0x88, 0x52, 0xfc,
	0x3e, 0x18, 0x71, 0x30, 0xf9, 0xb0, 0xb2, 0xab, 0xd9, 0x05, 0x86, 0x14, 0xe1, 0x15, 0xc0, 0x59,
	0x34, 0x1d, 0x07, 0x6a, 0x1f, 0x14, 0x58, 0xa0, 0x9b, 0x1b, 0x4f, 0x7e, 0xd0, 0x5e, 0x59, 0xe5,
	0x06, 0x51, 0x34, 0xc1, 0xe0, 0xb4, 0xa9, 0xb0, 0xc5, 0xad, 0x3d, 0xc2, 0x7e, 0x4a, 0x52, 0x2e,
	0x8e, 0x8f, 0x73, 0xf1, 0x0d, 0xd4, 0x54, 0x2d, 0xa9, 0x93, 0x7e, 0x95, 0x93, 0x2a, 0x39, 0xf5,
	0xda, 0x87, 0xd2, 0x85, 0x9f, 0x7c, 0x88, 0xc6, 0x3c, 0x8f, 0xbb, 0x4d, 0xb1, 0xc9, 0x1f, 0xb0,
	0x45, 0xa6, 0x8c, 0xbd, 0x57, 0x50, 0xcd, 0xca, 0xa5, 0xc7, 0xa3, 0xe4, 0xab, 0xc7, 0xa3, 0x33,
	0xe9, 0xcf, 0xb1, 0x57, 0x1f, 0x31, 0x5f, 0xf6, 0x5e, 0xfc, 0xd3, 0x7b, 0xdf, 0x00, 0x9d, 0xeb,
	0x5d, 0xb9, 0xf0, 0x85, 0x86, 0x55, 0xe5, 0x16, 0x55, 0xd0, 0xfb, 0xb6, 0x6d, 0x4a, 0xcc, 0x89,
	0x0a, 0x14, 0x2d, 0xf3, 0xc8, 0x45, 0x8d, 0x40, 0xd9, 0xef, 0xf6, 0x5c, 0xcc, 0x13, 0x78, 0x74,
	0x62, 0x59, 0x58, 0x68, 0xfc, 0xa6, 0x81, 0xce, 0x5f, 0xc8, 0xd5, 0x03, 0xfe, 0xc9, 0x5f, 0xaa,
	0x29, 0xad, 0x4a, 0x3e, 0x53, 0xf7, 0xa9, 0x5a, 0xea, 0x69, 0xc4, 0xe6, 0x97, 0xf6, 0x1f, 0x8f,
	0xed, 0xcf, 0x1a, 0xc0, 0xda, 0x24, 0xf6, 0xa1, 0x1c, 0x06, 0x89, 0x1f, 0x7b, 0x21, 0x07, 0x36,
	0x9a, 0xbb, 0xa9, 0xbb, 0xa5, 0xd0, 0x5e, 0x4e, 0xae, 0x08, 0xe2, 0xd6, 0x96, 0x68, 0xb4, 0x11,
	0xf8, 0x2a, 0x9e, 0x43, 0x35, 0x9a, 0xf9, 0xb1, 0xc7, 0x7b, 0x4b, 0x2d, 0x39, 0x4c, 0xa3, 0x38,
	0x2b, 0xbc, 0x97, 0x93, 0x6b, 0x52, 0xb6, 0x43, 0x7e, 0xd2, 0xa0, 0x9c, 0x26, 0x12, 0x0f, 0xc1,
	0x38, 0x0f, 0x23, 0x2f, 0x19, 0xa9, 0x85, 0x4c, 0xd5, 0x68, 0xb4, 0xec, 0x18, 0x7c, 0x4b, 0x98,
	0x78, 0x04, 0xb5, 0x79, 0x12, 0x07, 0xd3, 0xc9, 0x68, 0x63, 0x69, 0xf7, 0x72, 0xd2, 0x50, 0xa8,
	0x22, 0x7d, 0x09, 0x3b, 0xef, 0xa3, 0x28, 0xf4, 0xbd, 0x69, 0xca, 0xa2, 0x8a, 0x2a, 0xbd, 0x9c,
	0xac, 0xa5, 0x30, 0xd3, 0xb2, 0x12, 0x26, 0x50, 0xcd, 0x8a, 0x14, 0x5f, 0x43, 0x45, 0x15, 0x19,
	0xc5, 0x5c, 0xc0, 0x6e, 0xf3, 0xda, 0x56, 0x23, 0x51, 0x2c, 0x33, 0x82, 0x78, 0x9a, 0x92, 0xa7,
	0xd9, 0x0e, 0xfa, 0x8c, 0xf4, 0x19, 0x65, 0xff, 0x35, 0x14, 0xf9, 0xaf, 0xb0, 0x0a, 0xfa, 0x91,
	0xe5, 0xb4, 0x5c, 0xcc, 0x09, 0x80, 0xd2, 0xd0, 0x95, 0x7d, 0xbb, 0x8b, 0x9a, 0x30, 0xa0, 0x7c,
	0xe8, 0x38, 0x96, 0xd9, 0xb2, 0x31, 0x2f, 0x6a, 0x50, 0xe9, 0xb4, 0x5c, 0xd3, 0xed, 0x0f, 0x4c,
	0x2c, 0xec, 0xff, 0x99, 0x87, 0xca, 0x2a, 0xbf, 0x28, 0x43, 0xa1, 0xd5, 0xe9, 0x60, 0x8e, 0x38,
	0xc3, 0x93, 0x43, 0x57, 0xb6, 0xda, 0x34, 0x9b, 0x35, 0xa8, 0x0c, 0x4e, 0x2c, 0xb7, 0x7f, 0x6c,
	0xbd, 0xc3, 0x3c, 0x05, 0xee, 0xf4, 0xdf, 0xf6, 0x3b, 0x26, 0x16, 0xc8, 0x61, 0xe0, 0x74, 0xb0,
	0x48, 0x87, 0x63, 0xe7, 0x07, 0xd4, 0xe9, 0x60, 0x9e, 0x1e, 0x63, 0x89, 0xa6, 0x78, 0xf8, 0x46,
	0xba, 0x58, 0x16, 0x25, 0xc8, 0x5b, 0x36, 0x56, 0x78, 0xd8, 0x9d, 0x6e, 0x13, 0xab, 0x54, 0xa6,
	0xe5, 0x74, 0x5f, 0x3c, 0x47, 0xe0, 0x94, 0x87, 0x43, 0x34, 0xc8, 0xda, 0x36, 0xfb, 0x16, 0xd6,
	0xc8, 0xea, 0xca, 0x13, 0xbb, 0x8d, 0x3b, 0x69, 0x3f, 0x8e, 0xc4, 0x5d, 0x8a, 0x62, 0xbe, 0xc1,
	0x6b, 0xf4, 0x6b, 0x9b, 0x88, 0x1c, 0xd5, 0xc5, 0xeb, 0x14, 0xc0, 0x72, 0x4d, 0x14, 0x04, 0x74,
	0x5d, 0xfc, 0x1f, 0x01, 0x5d, 0xd7, 0xc4, 0x1b, 0x54, 0xa8, 0x79, 0xda, 0x1f, 0xba, 0x43, 0xbc,
	0xc9, 0x69, 0xec, 0x0e, 0xde, 0x22, 0x96, 0x23, 0xf1, 0x36, 0x01, 0xb6, 0xe3, 0x62, 0x9d, 0xf3,
	0x3a, 0x76, 0x07, 0xef, 0xf0, 0x27, 0x68, 0x76, 0xcd, 0x53, 0xdc, 0x23, 0xc1, 0xda, 0x8e, 0xdd,
	0x6e, 0xb9, 0x26, 0xde, 0x25, 0xea, 0xf0, 0x64, 0x80, 0xff, 0xe7, 0x20, 0x6f, 0xbb, 0x78, 0x8f,
	0xdb, 0x6e, 0x9d, 0xe2, 0x17, 0x7c, 0xe8, 0xdb, 0x78, 0x9f, 0x7c, 0xdb, 0xce, 0x89, 0xed, 0xe2,
	0x03, 0x0a, 0xf8, 0xce, 0x6c, 0x49, 0x7c, 0x48, 0xe0, 0xc0, 0xb1, 0xdd, 0x1e, 0x36, 0x88, 0xd8,
	0x69, 0xbd, 0xc3, 0x47, 0x62, 0x17, 0x40, 0x3d, 0xcb, 0xa8, 0xd5, 0xed, 0xe2, 0xe3, 0xf7, 0x25,
	0x7e, 0xd5, 0x97, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x33, 0x37, 0x0d, 0x23, 0x93, 0x09, 0x00,
	0x00,
}
